spring.application.name=inventoryservice

# MongoDB Configuration
spring.mongodb.uri=mongodb+srv://supunliyanage:supun1234@inventoryservice.kp2juls.mongodb.net/?appName=inventoryservice
spring.mongodb.database=${SPRING_MONGODB_DATABASE:inventorydb}

# Server Configuration
server.port=8081
