spring.application.name=INVENTORY-SERVICE

# MongoDB Configuration
spring.mongodb.uri=mongodb+srv://supunliyanage:supun1234@inventoryservice.kp2juls.mongodb.net/?appName=inventoryservice
spring.mongodb.database=${SPRING_MONGODB_DATABASE:inventorydb}

# Server Configuration
server.port=8081

# Eureka Configuration
eureka.client.service-url.defaultZone=https://ctseserviceregistryapp.purplecoast-1718a0fd.centralindia.azurecontainerapps.io/eureka/
eureka.instance.prefer-ip-address=true
